### ISSUE TITLE
Transport equation for a vector quantity with a source term

### ISSUE THREAD

**Issue by ahazra** [clawpack/riemann#106] opened 2015-08-19 15:48 UTC
I am planning to use clawpack/pyclaw library to solve a transport equation with a source term where a vector quantity will be transported.

$\vec q_t +\vec u(\vec x,t).\nabla \vec q = \psi(\vec q) $

I have a analytical solver for solving

$\vec q_t= \psi(\vec q)$

time array is pre-determined.

 primarily, I need to set-up the solver for transport equation of a vector quantity. Is there any readily available solver for that? or would any one please help me to set-up this step by step?

I need it urgently.

Thank you in advance.

Regards,

Arijit Hazra

**Comment by ketch** [comment] 2015-08-20 10:10
I'm closing this as it is a duplicate of https://github.com/clawpack/pyclaw/issues/521.  Please don't open duplicate issues, since it fragments the conversation.

**Closed by ketch** 2015-08-20 10:10 UTC
